(function(){
function HorusAudio(){
  this.enabled=true;
  this.ctx=null;
  this.bgm=null;
  this.scatterBgm=null;
  this.reelRoll=null
}
HorusAudio.prototype.init=function(){
  if(this.ctx)return;
  try{this.ctx=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}
};
HorusAudio.prototype.file=function(path,loop=false,volume=.28){
  if(!this.enabled)return null;
  const a=new window.Audio(path);
  a.loop=loop;
  a.volume=volume;
  a.play().catch(()=>{});
  return a
};
HorusAudio.prototype.stop=function(a){
  if(a){a.pause();a.currentTime=0}
};
HorusAudio.prototype.normalBgm=function(){
  if(!this.enabled)return;
  this.stop(this.scatterBgm);
  if(this.bgm){
    this.bgm.loop=true;
    this.bgm.play().catch(()=>{});
  }else{
    this.bgm=this.file('audio/normal/normal-bg.mp3',true)
  }
};
HorusAudio.prototype.scatterMode=function(){
  if(!this.enabled)return;
  this.stop(this.bgm);
  if(this.scatterBgm){
    this.scatterBgm.loop=true;
    this.scatterBgm.play().catch(()=>{});
  }else{
    this.scatterBgm=this.file('audio/scatter/scatter-bg.mp3',true)
  }
};
HorusAudio.prototype.startReelRoll=function(mode='normal'){
  if(!this.enabled)return;
  this.stop(this.reelRoll);
  this.reelRoll=this.file(`audio/${mode}/reel-roll.mp3`,true,mode==='scatter'?0.34:0.36);
};
HorusAudio.prototype.stopReelRoll=function(){this.stop(this.reelRoll);this.reelRoll=null};
HorusAudio.prototype.sfx=function(name,mode='normal',volume=.32){
  if(this.enabled)this.file(`audio/${mode}/${name}.mp3`,false,volume)
};
HorusAudio.prototype.setEnabled=function(v){
  this.enabled=v;
  if(!v){
    this.stop(this.bgm);
    this.stop(this.scatterBgm);
    this.stopReelRoll()
  }
};
window.HorusAudioEngine=HorusAudio
})();
