"use strict";
window.HorusConfig = Object.freeze({
  ROWS: 5, COLS: 6,
  STARTING_CREDIT: 100000, RESET_BELOW: 10000,
  DEFAULT_BET: 750,
  NORMAL_SPIN_DELAY: 980, TURBO_SPIN_DELAY: 120,
  NORMAL_TUMBLE_DELAY: 520, TURBO_TUMBLE_DELAY: 130,
  MAX_TUMBLE_ROUNDS: 30,
  SCATTER_TRIGGER: 4,
  SCATTER_BASE_SPINS: 15,
  SCATTER_EXTRA_PER_3: 5,
  BETS_BELOW_OR_EQUAL_4000_STEP: 100,
  BET_TRANSITION: 4000, BET_FIRST_HIGH: 5000,
  BET_HIGH_MULTIPLIER: 2,
  SYMBOL_BAG: ["eye","eye","ankh","ankh","scarab","scarab","sun","falcon","crown","lotus","horus"],
  SCATTER_PROBABILITY: 0.025,
  NORMAL_MIN_MATCH: 8,
  NORMAL_ROLL_STEP: 120,
  NORMAL_REEL_STOP_GAP: 135,
  NORMAL_WIN_FLASH_DELAY: 280
});
