"use strict";
window.HorusGameState = {
  IDLE:"IDLE", SPINNING:"SPINNING", TUMBLING:"TUMBLING",
  SCATTER_INTRO:"SCATTER_INTRO", SCATTER:"SCATTER", SCATTER_SPINNING:"SCATTER_SPINNING", SCATTER_TUMBLING:"SCATTER_TUMBLING",
  BIG_WIN:"BIG_WIN", SCATTER_END:"SCATTER_END"
};
