"use strict";
(function(){
 function GameEngine(){this.credit=new HorusCreditEngine();this.bet=new HorusBetEngine();this.symbols=new HorusSymbolEngine();this.wins=new HorusWinEngine(this.symbols);this.reels=new HorusReelEngine(this.symbols);this.grid=[];this.busy=false;this.turbo=false;this.auto=false;this.freeSpins=0;this.totalWin=0;this.state=HorusGameState.IDLE;this.sound=true;this.mode="NORMAL";this.audio=new HorusAudioEngine();this.horus=new HorusController();this.multiplier=1;this.normalMode=new HorusNormalMode(this);this.scatterMode=new HorusScatterMode(this);}
 GameEngine.prototype.setState=function(s){this.state=s;};
 GameEngine.prototype.startSpin=async function(){if(this.busy)return;if(this.freeSpins>0)return this.scatterMode.spin();return this.normalMode.spin();};
 GameEngine.prototype._runSpin=async function({free,mode}){if(this.busy)return;if(!free&&!this.credit.canAfford(this.bet.value)){this.ui.toast("Kredit tidak cukup untuk taruhan ini.");return;}this.busy=true;this.mode=mode;this.setState(mode==="SCATTER"?HorusGameState.SCATTER_SPINNING:HorusGameState.SPINNING);this.horus.set(mode==="SCATTER"?"ULTIMATE • SKY AVATAR":"GUARDIAN • IDLE");this.ui.setBusy(true);if(!free)this.credit.spend(this.bet.value);this.audio.spin();this.ui.update();this.grid=this.symbols.randomGrid(mode);await this.reels.animateSpin(this.grid,this.turbo,mode);this.audio.stop();const scat=this.wins.scatterCount(this.grid);this.setState(mode==="SCATTER"?HorusGameState.SCATTER_TUMBLING:HorusGameState.TUMBLING);const tumble=new HorusTumbleEngine({engine:this});const spinWin=await tumble.run(this.grid,mode);let finalWin=spinWin;if(mode==="SCATTER"){this.multiplier=HorusMultiplierEngine.decorate(this.grid);this.reels.render(this.grid,true);if(this.multiplier>1){finalWin=Math.floor(finalWin*this.multiplier);this.ui.addHistory("Multiplier x"+this.multiplier,finalWin);if(this.multiplier>=100)this.audio.big();}}this.credit.add(finalWin);if(finalWin>=this.bet.value*20){this.setState(HorusGameState.BIG_WIN);this.horus.set("DIVINE • SUPER WIN");this.audio.big();this.ui.bigWin(finalWin);}if(mode==="NORMAL"&&scat>=HorusConfig.SCATTER_TRIGGER){const added=this.scatterMode.addFreeSpins(scat);this.freeSpins+=added;this.setState(HorusGameState.SCATTER_INTRO);this.mode="SCATTER";this.horus.set("ULTIMATE • AWAKENED");this.audio.scatter();this.ui.toast(`${scat} SCATTER! +${added} FREE SPIN`);}else if(mode==="SCATTER"){this.freeSpins=Math.max(0,this.freeSpins-1);if(this.freeSpins===0){this.mode="NORMAL";this.setState(HorusGameState.SCATTER_END);this.horus.set("GUARDIAN • RETURN");this.ui.toast("Scatter selesai. Kembali ke Normal Mode.");}}if(this.credit.resetIfNeeded())this.ui.toast("Kredit di bawah Rp 10.000 → diisi ulang menjadi Rp 100.000.");this.busy=false;this.ui.setBusy(false);this.setState(this.freeSpins>0?HorusGameState.SCATTER:HorusGameState.IDLE);this.ui.update();if(this.auto){setTimeout(()=>this.startSpin(),this.turbo?100:450);}else if(this.freeSpins>0){setTimeout(()=>this.startSpin(),this.turbo?120:520);}};
 GameEngine.prototype.increaseBet=function(){if(!this.busy){this.bet.increase();this.ui.update();}};GameEngine.prototype.decreaseBet=function(){if(!this.busy){this.bet.decrease();this.ui.update();}};
 GameEngine.prototype.buyFree=function(){if(this.busy)return;const cost=this.bet.value*100;if(!this.credit.canAfford(cost)){this.ui.toast(`Kredit kurang untuk membeli Free Spin (${this.ui.fmt(cost)}).`);return;}this.credit.spend(cost);this.freeSpins=15;this.mode="SCATTER";this.setState(HorusGameState.SCATTER);this.horus.set("ULTIMATE • AWAKENED");this.audio.scatter();this.ui.update();this.ui.toast("15 FREE SPIN dibeli untuk demo.");};
 window.HorusGameEngine=GameEngine;
})();
