(function(){
  const $=s=>document.querySelector(s),fmt=n=>'Rp '+Math.max(0,Math.round(n||0)).toLocaleString('id-ID');
  const game=new HorusGameEngine();
  game.ui={
    fmt,
    toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(this.tt);this.tt=setTimeout(()=>t.classList.remove('show'),2200)},
    setBusy(b){$('#spinBtn').disabled=b;$('#buyBtn').disabled=b},state(s){document.body.dataset.state=s},
    update(){const scatter=game.mode==='SCATTER';$('#credit').textContent=fmt(game.credit.value);$('#bet').textContent=fmt(game.bet.value);$('#autoBtn').textContent=game.auto?'HENTIKAN AUTO':'AUTO';$('#autoBtn').classList.toggle('active',game.auto);$('#turboBtn').classList.toggle('active',game.turbo);$('#spinBtn').textContent=game.freeSpins>0?`FREE ${game.freeSpins}`:'SPIN';document.body.dataset.mode=scatter?'SCATTER':'NORMAL';$('#winMeter').style.width=Math.min(100,(game.totalWin/Math.max(1,game.bet.value))*2)+'%';$('#winMeterText').textContent=Math.min(100,Math.round((game.totalWin/Math.max(1,game.bet.value))*2))+'%';this.setBusy(game.busy)},
    markWins(wins){document.querySelectorAll('.cell.win').forEach(e=>e.classList.remove('win'));wins.flatMap(w=>w.cells).forEach(p=>{const e=document.querySelector(`.cell[data-r="${p.r}"][data-c="${p.c}"]`);if(e)e.classList.add('win')})},
    addHistory(label,amount){const h=$('#history'),d=document.createElement('div');d.innerHTML=`<span>${label}</span><strong>${amount?'+'+fmt(amount):'—'}</strong>`;h.prepend(d);while(h.children.length>8)h.lastElementChild.remove()},
    bigWin(amount){$('#bigWinAmount').textContent=fmt(amount);$('#bigWin').classList.add('show');setTimeout(()=>$('#bigWin').classList.remove('show'),1800)},
    showCenter(title,sub,kind='gold',duration=1300){return new Promise(resolve=>{const n=$('#reelNotification');n.className=`reel-notification ${kind} show`;n.innerHTML=`<span>${title}</span><strong>${sub}</strong>`;clearTimeout(this.nt);this.nt=setTimeout(()=>{n.classList.remove('show');resolve()},duration)})},
    showMultiplier(m){if(m.count)return this.showCenter('MULTIPLIER TERHUBUNG',`x${m.multiplier}`,'multiplier',1150)},
    showScatterEvent(data){const title=data.activation?'SCATTER MODE':'SCATTER TERHUBUNG';const sub=data.activation?`+${data.spins} FREE SPIN`:`${data.count} SCATTER • +${data.spins} FREE SPIN`;return this.showCenter(title,sub,'scatter',1450)},
    showScatterResult(data){return new Promise(resolve=>{const box=$('#scatterResult');$('#scatterResultTotal').textContent=fmt(data.totalWin);$('#scatterResultSpins').textContent=`${data.spinsPlayed} / ${data.totalSpins}`;$('#scatterResultMultiplier').textContent=`x${Math.max(1,data.maxMultiplier)}`;box.classList.add('show');const done=()=>{box.classList.remove('show');$('#scatterResultOk').removeEventListener('click',done);resolve()};$('#scatterResultOk').addEventListener('click',done,{once:true})})},
    openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show')},closeModal(){$('#modal').classList.remove('show')},
    paytable(){/* Values are intentionally shown in INFO/ATURAN so the character area stays clean. */}
  };
  game.horus=new HorusController();
  $('#spinBtn').onclick=()=>{game.audio.init();game.startSpin()};$('#betUp').onclick=()=>game.increaseBet();$('#betDown').onclick=()=>game.decreaseBet();
  $('#turboBtn').onclick=()=>{game.turbo=!game.turbo;game.ui.update()};$('#autoBtn').onclick=()=>{game.auto=!game.auto;game.ui.update();if(game.auto&&!game.busy)game.startSpin()};
  $('#buyBtn').onclick=()=>{if(game.busy)return;const cost=game.bet.value*100;game.ui.openModal('Beli Scatter',`<div class="scatter-buy"><div class="scatter-buy-art"><img src="assets/symbols/scatter.svg" alt="Scatter"></div><p class="scatter-buy-label">HARGA SCATTER</p><strong class="scatter-buy-price">${fmt(cost)}</strong><p class="scatter-buy-note">Setelah dikonfirmasi, Scatter langsung berjalan otomatis tanpa tombol FREE SPIN.</p><div class="scatter-buy-actions"><button id="scatterCancel" class="scatter-cancel" type="button">✕</button><button id="scatterConfirm" class="scatter-confirm" type="button">✓</button></div></div>`);$('#scatterCancel').onclick=()=>game.ui.closeModal();$('#scatterConfirm').onclick=async()=>{game.ui.closeModal();game.audio.init();await game.buyFree()}};
  $('#soundBtn').onclick=()=>{game.audio.init();game.audio.setEnabled(!game.audio.enabled);$('#soundBtn').textContent=game.audio.enabled?'🔊':'🔇';if(game.audio.enabled)game.audio.sfx('button','ui')};
  $('#closeModal').onclick=()=>game.ui.closeModal();$('#modal').onclick=e=>{if(e.target===$('#modal'))game.ui.closeModal()};
  const rules=`<h4>Cara Bermain</h4><ul><li>Grid 5×5.</li><li>Minimal 7 simbol identik membentuk kombinasi win pada putaran biasa.</li><li>Simbol menang terlihat dahulu, lalu dihapus dengan tumble/gravity dan simbol baru masuk dari atas.</li><li><b>Minimal 4 simbol Scatter pada satu hasil putaran langsung dihitung sebagai Scatter terhubung.</b> Posisi Scatter tidak harus berdampingan.</li></ul><h4>Perhitungan Free Spin</h4><ul><li>4–5 Scatter = +15 Free Spin.</li><li>6–7 Scatter = +20 Free Spin.</li><li>8–9 Scatter = +25 Free Spin.</li><li>10–11 Scatter = +30 Free Spin.</li><li>Perhitungan berlanjut per tier berikutnya.</li><li>Buy Scatter langsung memulai Free Spin secara otomatis.</li></ul><h4>Nilai Simbol</h4><div class="rules-paytable">${game.symbols.symbols.filter(s=>!s.scatter).map(s=>`<div><img src="${s.svg}" alt="${s.name}"><span>${s.name}</span><b>×${s.value}</b></div>`).join('')}</div><h4>Multiplier Scatter</h4><ul><li>Multiplier hanya dihitung jika simbol multiplier berada pada kombinasi win yang benar-benar terhubung.</li><li>Symbol Scatter sendiri tidak menampilkan multiplier.</li><li>x1–9 hijau, x10–19 biru, x20–49 ungu, x50–99 magenta, x100–249 gold, x250–499 cyan, x500–999 solar, x1000 divine.</li></ul><h4>Bet & Kredit</h4><ul><li>Mulai Rp100.000 virtual.</li><li>Sampai Rp4.000: +Rp100.</li><li>Rp4.000 → Rp5.000 → Rp10.000 → selanjutnya ×2.</li><li>Jika saldo turun di bawah Rp10.000, demo diisi ulang menjadi Rp100.000.</li></ul>`;
  $('#rulesBtn').onclick=()=>game.ui.openModal('Aturan Game',rules);$('#infoBtn').onclick=()=>game.ui.openModal('Cara Bermain',rules);
  const preload=['assets/symbols/horus.svg','assets/symbols/eye.svg','assets/symbols/ankh.svg','assets/symbols/scarab.svg','assets/symbols/sun.svg','assets/symbols/falcon.svg','assets/symbols/crown.svg','assets/symbols/lotus.svg','assets/symbols/scatter.svg','assets/horus/horus-idle.webp','assets/horus/horus-spin.webp','assets/horus/horus-win.webp','assets/horus/horus-bigwin.webp','assets/horus/horus-scatter.webp','assets/horus/horus-ultimate.webp','assets/backgrounds/normal-bg.png','assets/backgrounds/scatter-bg.png'];
  function preloadImages(){return Promise.all(preload.map(src=>new Promise(resolve=>{const im=new Image();im.onload=resolve;im.onerror=resolve;im.src=src})))}function finishLoading(){const screen=$('#loadingScreen');screen.classList.add('loaded');setTimeout(()=>screen.remove(),500);game.start()}
  (async()=>{await preloadImages();setTimeout(finishLoading,450)})();window.HorusGame=game;
})();
