"use strict";
(function(){
 function ReelEngine(symbolEngine){this.symbols=symbolEngine;this.root=document.querySelector("#reels");}
 ReelEngine.prototype.createCell=function(cell,fresh=false){const s=this.symbols.get(cell.id||cell);const d=document.createElement("div");d.className="cell"+(fresh?" new":"");d.dataset.id=s.id;d.innerHTML=`<svg viewBox="0 0 100 100" aria-label="${s.name}"><use href="${s.svg}"></use></svg>`;if(s.scatter){const l=document.createElement("div");l.className="label";l.textContent="SCATTER";d.appendChild(l);}if(cell.multiplier>1){const m=document.createElement("div");m.className="multiplier "+HorusMultiplierEngine.tier(cell.multiplier);m.textContent="x"+cell.multiplier;d.appendChild(m);}return d;};
 ReelEngine.prototype.render=function(grid,fresh=false){this.root.innerHTML="";for(let c=0;c<HorusConfig.COLS;c++){const reel=document.createElement("div");reel.className="reel";reel.dataset.col=c;for(let r=0;r<HorusConfig.ROWS;r++)reel.appendChild(this.createCell(grid[r][c],fresh));this.root.appendChild(reel);}};
 ReelEngine.prototype._setColumn=function(c,ids){const reel=this.root.children[c];if(!reel)return;for(let r=0;r<HorusConfig.ROWS;r++){const cell=reel.children[r],id=typeof ids[r]==="string"?ids[r]:ids[r].id;cell.replaceWith(this.createCell(typeof ids[r]==="string"?{id}:ids[r]));}};
 ReelEngine.prototype._randomColumn=function(mode){return Array.from({length:HorusConfig.ROWS},()=>({id:this.symbols.weighted(mode==="SCATTER"?HorusConfig.SCATTER_SCATTER_PROB:HorusConfig.NORMAL_SCATTER_PROBABILITY),multiplier:0}));};
 ReelEngine.prototype.animateSpin=async function(finalGrid,turbo=false,mode="NORMAL"){this.render(this._randomColumnGrid(mode));const step=turbo?55:HorusConfig.NORMAL_ROLL_STEP,gap=turbo?35:HorusConfig.NORMAL_REEL_STOP_GAP,cycles=turbo?2:4;const tasks=[];this.root.querySelectorAll(".reel").forEach(e=>e.classList.add("rolling"));for(let c=0;c<HorusConfig.COLS;c++){tasks.push((async()=>{for(let i=0;i<cycles+c;i++){this._setColumn(c,this._randomColumn(mode));await new Promise(r=>setTimeout(r,step));}this._setColumn(c,finalGrid.map(row=>row[c]));const reel=this.root.children[c];if(reel){reel.classList.remove("rolling");reel.classList.add("stopped");setTimeout(()=>reel.classList.remove("stopped"),250);}})());await new Promise(r=>setTimeout(r,gap));}await Promise.all(tasks);this.render(finalGrid);};
 ReelEngine.prototype._randomColumnGrid=function(mode){return Array.from({length:HorusConfig.ROWS},()=>Array.from({length:HorusConfig.COLS},()=>({id:this.symbols.weighted(mode==="SCATTER"?HorusConfig.SCATTER_SCATTER_PROB:HorusConfig.NORMAL_SCATTER_PROBABILITY),multiplier:0})));};
 ReelEngine.prototype.removeWinningSymbols=function(grid,wins){const remove=new Set(wins.flatMap(w=>w.cells.map(p=>p.r+","+p.c)));for(let r=0;r<HorusConfig.ROWS;r++)for(let c=0;c<HorusConfig.COLS;c++)if(remove.has(r+","+c))grid[r][c]=null;};
 ReelEngine.prototype.collapse=function(grid,mode){for(let c=0;c<HorusConfig.COLS;c++){const kept=[];for(let r=HorusConfig.ROWS-1;r>=0;r--)if(grid[r][c])kept.push(grid[r][c]);while(kept.length<HorusConfig.ROWS)kept.push({id:this.symbols.weighted(mode==="SCATTER"?HorusConfig.SCATTER_SCATTER_PROB:HorusConfig.NORMAL_SCATTER_PROBABILITY),multiplier:0});for(let r=HorusConfig.ROWS-1,i=0;r>=0;r--,i++)grid[r][c]=kept[i];}}
 window.HorusReelEngine=ReelEngine;
})();
